[
  {":0:unknown_function Function ExUnit.Callbacks.__merge__/3 does not exist."},
  {":0:unknown_function Function ExUnit.CaseTemplate.__proxy__/2 does not exist."},
  {"lib/dj_rumble/rooms/supervisor.ex", :callback_type_mismatch, 0},
  {"lib/dj_rumble/rounds/supervisor.ex", :callback_type_mismatch, 0},
  {"lib/dj_rumble/rooms/supervisor.ex", :callback_type_mismatch, 14},
  {"lib/dj_rumble/rounds/supervisor.ex", :callback_type_mismatch, 14},
  {"lib/dj_rumble_web/controllers/user_settings_controller.ex", :app_call, 45},
  {"lib/dj_rumble_web/live/live_helpers.ex", :call, 24},
  {"lib/dj_rumble_web/live/room_live/index.html.leex", :call, 1},
  {"lib/dj_rumble_web/live/room_live/show.html.leex", :call, 3},
  {"lib/dj_rumble_web/live/room_live/show.html.leex", :call, 9},
  {"lib/dj_rumble_web/live/room_live/show.html.leex", :call, 16},
  {"lib/dj_rumble_web/live/room_live/show.html.leex", :call, 19},
  {"lib/dj_rumble_web/live/room_live/show.html.leex", :call, 24},
  {"lib/dj_rumble_web/live/room_live/show.html.leex", :call, 33},
  {"lib/dj_rumble_web/live/room_live/show.html.leex", :call, 38},
  {"lib/dj_rumble_web/live/room_live/show.html.leex", :call, 40},
  {"lib/dj_rumble_web/live/room_live/show.html.leex", :call, 49}
]
