name: Code analysis CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  lint:

    name: Lint and static analysis
    runs-on: ubuntu-latest

    container:
      image: elixir:1.9.1-slim

    steps:
      - uses: actions/checkout@v2
      - name: Set up Elixir
        uses: erlef/setup-elixir@v1
        with:
          elixir-version: '1.10.4'
          otp-version: '23.0'
      - name: Install Dependencies
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get
      - name: Run code analysis
        run: |
          make lint.ci
